Algoritmo "raio"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/04/2026
Var
   Raio, Perimetro, Area:real


Inicio
   Escreval("Informe o raio:")
   leia(Raio)
   Perimetro <- 2*pi*Raio
   Area<- pi*Raio^2
   
   Escreval("A area é igual a:", Area:2:2, " E o perimetro:", Perimetro:1:2)

Fimalgoritmo